#!/bin/bash

mkdir -p traefik/certificates
cd traefik/certificates
mkcert --cert-file localhost.pem --key-file localhost-key.pem localhost "*.localhost" "*.dev.localhost" "*.ci.localhost" "*.prod.localhost" 127.0.0.1 ::1 host.docker.internal
cd ../..
mkcert -install
